export const data = [
  {
    id: 1,
    title: 'Large Detroit Style Pizza',
    progress: 20,
    amount: 31.43,
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 2,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    progress: 35,
    amount: 12.99,
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 3,
    title: 'Family Sized Lobster Dinner',
    progress: 75,
    amount: 320.0,
    status: 'In Progress',
    name: 'Alexander',
  },
  {
    id: 4,
    title: 'Style Pizza',
    progress: 40,
    amount: 31.43,
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 5,
    title: 'Club With Fries. Pickles, extra side avacado',
    progress: 10,
    amount: 12.99,
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 6,
    title: 'Lobster Dinner',
    progress: 25,
    amount: 320.0,
    status: 'In Progress',
    name: 'Alexander',
  },
  {
    id: 7,
    title: 'Pizza pepperoni',
    progress: 30,
    amount: 31.43,
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 8,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    progress: 60,
    amount: 12.99,
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 9,
    title: 'Family Sized Lobster Dinner',
    progress: 15,
    amount: 320.0,
    status: 'In Progress',
    name: 'Alex',
  },
  {
    id: 10,
    title: 'Large Detroit Style Pizza',
    progress: 20,
    amount: 31.43,
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 11,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    progress: 55,
    amount: 12.99,
    status: 'Delivered',
    name: 'Dima',
  },
  {
    id: 12,
    title: 'Family Sized Dinner',
    progress: 30,
    amount: 320.0,
    status: 'Stopped',
    name: 'Alex',
  },
];
